insert into movie(title, year, genres)
values ('Toy Story', 1994, 'ADVENTURE|ANIMATION|CHILDREN|COMEDY|FANTASY'),
       ('Jumanji', 1994, 'ADVENTURE|CHILDREN|FANTASY'),
       ('Grumpier Old Men', 1994, 'COMEDY|ROMANCE'),
       ('Waiting to Exhale', 1995, 'COMEDY|DRAMA|ROMANCE'),
       ('Father of the Bride Part II', 1995, 'COMEDY'),
       ('Heat', 1995, 'ACTION|CRIME|THRILLER'),
       ('Sabrina', 1995, 'COMEDY|ROMANCE'),
       ('Tom and Huck', 1995, 'ADVENTURE|CHILDREN'),
       ('Sudden Death', 1995, 'ACTION'),
       ('GoldenEye', 1995, 'ACTION|ADVENTURE|THRILLER'),
       ('American President, The', 1995, 'COMEDY|DRAMA|ROMANCE'),
       ('Dracula: Dead and Loving It', 1995, 'COMEDY|HORROR'),
       ('Balto', 1995, 'ADVENTURE|ANIMATION|CHILDREN'),
       ('Nixon', 1995, 'DRAMA'),
       ('Cutthroat Island', 1994, 'ACTION|ADVENTURE|ROMANCE'),
       ('Casino', 1995, 'CRIME|DRAMA'),
       ('Sense and Sensibility', 1995, 'DRAMA|ROMANCE'),
       ('Four Rooms', 1995, 'COMEDY'),
       ('Ace Ventura: When Nature Calls', 1995, 'COMEDY'),
       ('Money Train', 1995, 'ACTION|COMEDY|CRIME|DRAMA|THRILLER'),
       ('Get Shorty', 1995, 'COMEDY|CRIME|THRILLER'),
       ('Copycat', 1995, 'CRIME|DRAMA|HORROR|MYSTERY|THRILLER'),
       ('Assassins', 1995, 'ACTION|CRIME|THRILLER'),
       ('Powder', 1995, 'DRAMA|THRILLER'),
       ('Leaving Las Vegas', 1995, 'DRAMA|ROMANCE'),
       ('Othello', 1995, 'DRAMA'),
       ('Now and Then', 1995, 'CHILDREN|DRAMA'),
       ('Persuasion', 1995, 'DRAMA|ROMANCE'),
       ('City of Lost CHILDREN, The, Cité des enfants perdus, La)', 1995, 'ADVENTURE|DRAMA|FANTASY|MYSTERY|THRILLER'),
       ('Shanghai Triad, Yao a yao yao dao waipo qiao)', 1995, 'CRIME|DRAMA'),
       ('Dangerous Minds', 1995, 'DRAMA'),
       ('Twelve Monkeys, a.k.a. 12 Monkeys)', 1995, 'MYSTERY|THRILLER|THRILLER'),
       ('Babe', 1995, 'CHILDREN|DRAMA'),
       ('Carrington', 1995, 'DRAMA|ROMANCE'),
       ('Dead Man Walking', 1995, 'CRIME|DRAMA'),
       ('Across the Sea of Time', 1995, 'DOCUMENTARY|IMAX'),
       ('It Takes Two', 1995, 'CHILDREN|COMEDY'),
       ('Clueless', 1995, 'COMEDY|ROMANCE'),
       ('Cry, the Beloved Country', 1995, 'DRAMA'),
       ('Richard III', 1995, 'DRAMA|WAR'),
       ('Dead Presidents', 1995, 'ACTION|CRIME|DRAMA'),
       ('Restoration', 1995, 'DRAMA'),
       ('Mortal Kombat', 2000, 'ACTION|ADVENTURE|FANTASY'),
       ('To Die For', 2000, 'COMEDY|DRAMA|THRILLER'),
       ('How to Make an American Quilt', 2010, 'DRAMA|ROMANCE'),
       ('Seven, a.k.a. Se7en)', 2000, 'MYSTERY|THRILLER'),
       ('Pocahontas', 1995, 'ANIMATION|CHILDREN|DRAMA|MUSICAL|ROMANCE'),
       ('When Night Is Falling', 2015, 'DRAMA|ROMANCE'),
       ('Usual Suspects, The', 1995, 'CRIME|MYSTERY|THRILLER');
